// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  quem_somos: dynamic(() => import("./QuemSomos")),
  title: dynamic(() => import("./Title")),
};
